### ISSUE TITLE
Cancel on next checkpoint

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#10]
Attention: this issue is one of those imported from the old hashcat trac ticketing system.

OP: unix-ninja
Date of report: 2015-10-14
Original post:
"We should add a feature to the hashcat family of apps where we can press a hotkey to quit after the next "checkpoint" rather than immediately. Maybe (c) for cancel at checkpoint?"

This ticket was accepted by 'atom' on the trac ticketing system. 
Thx

**Comment by jsteube** [comment]
OK, merged. Good work, thanks!
