### ISSUE TITLE
PBKDF2-HMAC-RipeMD160 not working with Nvidia Titan X

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#100]
This issue was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | tonys |
| Title:                                  | Unable to crack PBKDF2-HMAC-RipeMD160 in cudaHashcat 1.36 |
| Ticket number:                  | 642 |
| Date reported:                  | 2015-07-25T00:38:32+02:00 |
| **Description**:                 | I'm refering to ​this [file](https://hashcat.net/misc/example_hashes/hashcat_ripemd160_aes.tc) (PBKDF2-HMAC-RipeMD160 AES). It cracks fine in 1.31, though.<br><br> I'm running two Titan X's with ForceWare 350.12. |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | atom       | It's hard to reproduce/fix since I do not have a Titan X for testing. But, it works fine on my GTX 980 which uses the same sm_52 chipset as the Titan X does.<br><br>Are you sure you're using the right mode -m 6211 ? |

**Comment by jsteube** [comment]
Should be fixed with latest github version

**Comment by Xanadrel** [comment]
Works for me with 1.36, 2.01, 2.10b32

Config:
Windows 7
1x Titan X
Driver 361.43

**Comment by philsmd** [comment]
I close this ticket because:
1. on trac we didn't get a respond (after atom's question -- see comment)
2. it is working on a system with titan x and the exact same test

Please reopen if this is still a problem (and you have more details on how to reproduce etc).
