### ISSUE TITLE
hardware monitor not working when using -d argument

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#102]
This issue was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | beepboop |
| Title:                                  | HWMon.GPU monitoring different GPUs to those set in --gpu-devices command |
| Ticket number:                  | 659 |
| Date reported:                  | 2015-09-11T12:17:27+02:00 |
| **Description**:                 | When using two GTX690s but running an attack with the --gpu-devices=2,4 command (which I believe to be the two GPUs on the second card in my setup), the HWMon.GPU1 is always listed with low 'Util' values as well as a low temp, although other tools (MSI Afterburner) show the GPU is in use and the temperature is closer to that of the other active GPU;<br><br>C:\HashCat_137>cudahashcat64.exe -w 3 -a 3 -m 1000 X\<\<\<\<\<\<\<\<REDACTED HASH\>\>\>\>\>\>\>\>\>X -1 ?a ?1?1?1?1?1?1?1?1 --gpu-devices=2,4<br>cudaHashcat v1.37 starting...<br><br>Device # 2: skipped by user<br>Device # 2: GeForce GTX 690, 2048MB, 1019Mhz, 8MCU<br>Device # 5: skipped by user<br>Device # 4: GeForce GTX 690, 2048MB, 1019Mhz, 8MCU<br><br>Hashes: 1 hashes; 1 unique digests, 1 unique salts<br>Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates<br><br>Session.Name...: cudaHashcat<br>Status.........: Running<br>Input.Mode.....: Mask (?1?1?1?1?1?1?1?1) [8]<br>Hash.Target....: 880806481e75dccbe3d26bcf34b9c849<br>Hash.Type......: NTLM<br>Time.Started...: Fri Sep 11 11:05:08 2015 (4 secs)<br>Time.Estimated.: Sat Sep 19 11:50:49 2015 (8 days, 0 hours)<br>Speed.GPU.# 1...:  4853.9 MH/s<br>Speed.GPU.# 2...:  4799.8 MH/s<br>Speed.GPU.#*...:  9653.7 MH/s<br>Recovered......: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts<br>Progress.......: 47316992000/6634204312890625 (0.00%)<br>Rejected.......: 0/47316992000 (0.00%)<br>Restore.Point..: 4718592/735091890625 (0.00%)<br>HWMon.GPU.# 1...:  0% Util, 53c Temp, 1560rpm Fan<br>HWMon.GPU.# 2...: 99% Util, 69c Temp, 1890rpm Fan |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | beepboop       | Just trying this with different combinations of my 4 GPUs I get the same issue if the first GPU listed in the gpu-devices command is 2; if the first is 1 then the HWMon.GPU2 = 0% Util  |
| 2.                               | atom       | So, that error occurs only if you use -d ? |
| 3.                               | beepboop       |  Seems to be, although even then, it only occurs with certain combinations of GPUs. Each GTX690 has two GPUs and some combinations seem to be OK and others not (although the speed listed for each GPU is comparable to the others so it does seem to be working OK):<br><br>1+2 = HWMon.GPU.1 = 99% - HWMon.GPU.2 = 0%<br>1+3 = HWMon.GPU.1 = 99% - HWMon.GPU.2 = 0%<br>1+4 = HWMon.GPU.1 = 99% - HWMon.GPU.2 = 99%<br>2+3 = HWMon.GPU.1 = 99% - HWMon.GPU.2 = 99%<br>2+4 = HWMon.GPU.1 = 0% - HWMon.GPU.2 = 99%<br>3+4 = HWMon.GPU.1 = 0% - HWMon.GPU.2 = 99%<br><br>Looks like the problem is when 2 and 3 is used in combination with another?<br><br>If I run it with -d 1,2,3,4 (or without the command at all) then they all read as 99% |

**Comment by jsteube** [comment]
@ OP if you read this, we think this is fixed with hashcat v3.00. If not, please reopen the ticket

**Comment by darianf01** [comment]
this is not fixed on 3.10.
tried with a gtx1060 and 550ti
while running with -d 1 (e.g. 1060) i get the h/w monitor of the 550ti but hashcat running on1060.
while running with -d 2 (e.g. 550ti) i get stats for the 1060, while hashcat runs on 550ti.
windows 10 64 bit (and nvidia 373.06, although i believe this does not matter)

**Comment by jsteube** [comment]
Please retry with this version: https://hashcat.net/beta/
