### ISSUE TITLE
DCC2 example hash not working

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#103]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | rfrogman |
| Title:                                  | oclHashcat v1.36 DCC2 Signature unmatch |
| Ticket number:                  | 664 |
| Date reported:                  | 2015-10-09T16:19:01+02:00 |
| **Description**:                 |  I am receiving the following error using your sample DCC2 Hash.<br><br>oclhashcat -m 2100 --force $DCC2$10240#tom#e4e938d12fe5974dc42a90120bd9c90f "hashcat"<br>oclHashcat v1.36 starting...<br><br>WARNING: Hash '0240#tom#e4e938d12fe5974dc42a90120bd9c90f': Signature unmatched<br><br>ERROR: No hashes loaded |

**Comment by philsmd** [comment]
you need to quote the hash if you use it on the command line, e.g. '$DCC2$10240#tom#e4e938d12fe5974dc42a90120bd9c90f'

We should close this ticket. This is pebcak

**Comment by philsmd** [comment]
also please do not report any problems while using --force.

Anybody has something against closing this ticket? (IMO this is of course not a oclHashcat problem, but a shell escape problem $DCC2 and $1 are interpreted as variables by your shell interpreter)

**Comment by jsteube** [comment]
This is obviosly user-defined error, not a bug.
