### ISSUE TITLE
--keyspace problem in oclHashcat or FAQ

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#104]
This issue was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | a.ryabkov |
| Title:                                  | keyspace in combinator attack |
| Ticket number:                  | 666 [sigh] |
| Date reported:                  | 2015-10-15T23:09:32+02:00 |
| **Description**:                 |  Acc[or]ding to [the hashcat FAQ](https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_keyspace) in this mode [-a 1] we must have number of words in left_wordlist but when i start real tools i found that its always return biggest wordlist...<br>is it [a] bug?<br><br>output...<br>$ wc -l dict_*<br>6 dict_1<br>256 dict_2<br>1900031 dict_3<br>267922707 dict_4<br>269823000<br><br>$ ./cudaHashcat64.bin -a 1 -m 0 --keyspace example0.hash ../dict_2 ../dict_3 1900032<br>$ ./cudaHashcat64.bin -a 1 -m 0 --keyspace example0.hash ../dict_3 ../dict_2 1900032<br>$ ./cudaHashcat64.bin -a 1 -m 0 --keyspace example0.hash ../dict_3 ../dict_4 267922708<br>$ ./cudaHashcat64.bin -a 1 -m 0 --keyspace example0.hash ../dict_4 ../dict_3 267922708<br>$ ./cudaHashcat64.bin -a 1 -m 0 --keyspace example0.hash ../dict_2 ../dict_3 1900032<br>$ ./cudaHashcat64.bin -a 1 -m 0 --keyspace example0.hash ../dict_3 ../dict_2 1900032<br>$ ./cudaHashcat64.bin -a 1 -m 0 --keyspace example0.hash ../dict_3 ../dict_4 267922708<br>$ ./cudaHashcat64.bin -a 1 -m 0 --keyspace example0.hash ../dict_4 ../dict_3 267922708 |

**Comment by jsteube** [comment]
That's correct, the FAQ needs to be updated. This is some feature a while ago. It's as you said, it's always the bigger wordlist

**Comment by philsmd** [comment]
I changed the text within the [FAQ section](https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_keyspace) to:
"-a 1 – number of words of the larger word list out of the 2 word lists specified (left_wordlist, right_wordlist)"

I will close this issue, because now it should be very clear.
