### ISSUE TITLE
BUG?: Peoplesoft -m 133 | Segmentation Fault

### ISSUE THREAD

**Issue by Zer0Tolerance** [hashcat/oclHashcat#105]
A wordlist run with this hash type throws a segfault.
Brute/mask attack is okay although it does run for a few seconds < 15sec with selected wordlists before once again hitting a segfault.

./hashcat-cli64.bin -a 0 -m 133 ../hash.txt ~/wordlists/rockyou-top50k.txt 
Initializing hashcat v2.00 with 4 threads and 32mb segment-size...

Added hashes from file ../hash.txt: 1 (1 salts)

[s]tatus [p]ause [r]esume [b]ypass [q]uit => Segmentation fault

Hope you can replicate it
Hash used::  uXmFVrdBvv293L9kDR3VnRmx4ZM=:hashcat

**Comment by jsteube** [comment]
This is the wrong project, you did post to the oclHashcat project. Please open the ticket again in hashcat.
