### ISSUE TITLE
support for Oracle PeopleSoft cookie tokens

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#111]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | hamid |
| Title:                                  | Extending SHA1 salt length limit (needed for Oracle PeopleSoft tokens) |
| Ticket number:                  | 678 |
| Date reported:                  | 2015-11-18T23:43:19+01:00 |
| **Description**:                 |  Recently a research has been released that explains an offline attack against Oracle PeopleSoft cookie tokens, allowing generating custom cookies, as explained [here](http://erpscan.com/press-center/blog/peoplesoft-security-part-3-peoplesoft-sso-tokenchpoken-attack/)<br><br>sample python script to crack the hash is also provided.<br><br>required algorithm is already in hashcat (mode 140) which is sha1(salt+unicode(password)) but the problem is [the] length of the salt (237 hex characters) which seems to be above current limitation of hashcat, causing " Line-length exception" error.  |

**Comment by jsteube** [comment]
Support added to latest beta
