### ISSUE TITLE
generate every (n)th word for distributed cracking

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#113]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | nigelpinkerton |
| Title:                                  | Feature request: Only generate every '(n)th word' argument |
| Ticket number:                  | 680 |
| Date reported:                  | 2015-11-23T22:29:02+01:00 |
| **Description**:                 |  Hi,<br><br>I'm slowly working on a wrapper for distributed hashcat cracking. The skip, limit and keyspace features that were recently added make parallel cracking much easier.<br><br>However, one small feature that could further simplify parallel hashing implementation would be a 'generate every (n)th word' option. This would also be handy to have in some of the hash-cat utilities like mask-processor. Admittedly it's just a 'nice to have' feature, so I've set this request at the lowest priority.<br><br>The benefits:<br>- You could stream (rather than batch) words to remote computers (probably using something as simple as a named pipe over ssl, or websockets if you want to get fancy), and rapidly alter distribution parameters as nodes go offline or are added<br>- The above also sidesteps complexity due to heterogeneity of computers in the distributed system (i.e. no worrying about varying batch/task sizes because of differing hash rates)<br>- Failure tolerance and recovery would be easier to implement and quicker (wouldn't have to poll for server status but could just stream [parsed] stdout back in real-time)<br><br>I hope that makes sense.<br>Just to clarify, the implementation I'm thinking of is along the lines of writing a wrapper that ssh'es into remote machines, starts hashcat in stdin mode reading from a named pipe, and streams generated words to that named pipe (in some automated way).<br>Or even have no communication (other than monitoring) at all, as you could just configure:<br><br>- node 1 hashing words 1,11,21 etc.<br>- node 2 hashing words 2,12,22 etc.<br>- and so on for a 10 node cluster<br><br>Cheers,<br>Nigel |

**Comment by jsteube** [comment]
Please use -s and -l for distrubuted computing, it's really the best way to do is.
