### ISSUE TITLE
missing cracks when using hybrid attack with many GPUs (e.g. 24)

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#114]
This issue was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | cryptolovi |
| Title:                                  | if dictionary entries are less then the amount of gpus when doing hybrid attacks this will result in none found |
| Ticket number:                  | 682 |
| Date reported:                  | 2015-11-27T10:49:38+01:00 |
| **Description**:                 | I'm not sure where the boundary of this error starts, but with a system with 2 GPU's I'm not able to reproduce the error.<br><br>The test:<br>- A system with 24 GPUs.<br>- A hash file 'hash.m100' with created sha1 hash values for this test.<br>- A dictionary file 'dictionary.txt' created with words for this test.<br><br>If the 'dictionary.txt' contains only 23 entries (or less) and we start an hybrid attack;<br><br>cudaHashcat64.bin -m 100 hash.m100 -a 6 dictionary.txt ?d<br>or-a 7<br><br>Not a single hash will be found. At[ ]least two hashes for each attack should be found; namely:<br>f6513e8720858f151c24a0eb725a6415193b01ad:hybrid1<br>a6f4483a5baaeb3a729865b8c3d39ab8dccb9aff:hybrid9 for -a 6<br>and<br>7e6b724af33fb4cc0d688101330a7006302ca9f4:1hybrid<br>d61e46b1dd091483482f6b53c8491711c632c932:9hybrid for -a 7<br><br>The last word in the attached dictionary is word20, if we add another entry to the dictionary, for example word21 and therefor supply a dictionary with 24 entries (the same or greater as the amount of GPUs) the above attacks will find all 4 hash values.<br><br>Of[ ]course, it's questionable if this happens in daily practice (using dictionaries with less entries then the amount of GPUs), but still a GPU should find something.<br><br>(when using combination attack -a 1, this problem doesn't occur even with using dictionaries [that] have 1 line only) |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | philsmd       |  Can you please let us know what you mean by a system with 24 GPUs?<br><br>Is this a distributed system? Are you using hashtopus / hashstack or similar wrappers? As far as I know there are several limits that prevents us to have that many GPUs on a single system: the driver limits, motherboard/BIOS support, PCI connections etc<br><br>By the way, you can also select which cards to use by specifying a comma separated list to oclHashcat: -d 1,3,5,7. What happens if you limit the number of devices this way? Does the problem still occur with e.g. 12, 20 etc devices ? With which amount of devices does it start to happen for you (when trying with -d [list]) ?<br><br>Another test you can do: what if you play with the -n/-u parameters (-n 1 -u 1 for instance) ?<br><br>Thx |
| 2. | cryptolovi |  A system where one single instance of hashcat uses 24 GPUs, without hashtopus or any other wrappers is what I mean with a system with 24 GPUs. The driver limit is currently 28 (nvidia).<br><br>I will go do some testing with the paramaters and try to track down at which number of devices the problem does occur. |
| 3. | cryptolovi |  Playing with -n 1 and -u 8 or other values don't have any affect on the result as described above.<br><br>-d only goes as far as 8. With -d 1,2,3,4,5,6,7,8 and with a dictionary.txt with less then 8 entries I am also not able to reproduce the error.<br><br>Maybe I could do some more test if I could use -d above 8, to see what causes the none founds in this particular case. |
| 4. | cryptolovi | I ran the tests again with a 9 GPUs system. This time with a multiple nvidia kernel module loading only for 9 GPU PCI ids.<br><br>With a dictionary of 8 entries the error is reproducible. When adding a 9th entry to the dictionary the -a 6 and -a 7 will find the hash values again.<br><br>The boundary of this error lies on the 9th plus GPU. |
| 5. | philsmd | Thanks for these details.<br><br>Now the devs need to reproduce it (I currently can't because I have no such system with that many GPUs) and it will hopefully be fixed soon. |

---

Files:
[Attached files by cryptolovi](https://github.com/hashcat/oclHashcat/files/83396/a.zip)

**Comment by philsmd** [comment]
Note: the -d limit (was previously limited to the range 0-8) was removed with the newest git/beta version (2.10).

Maybe we can kindly ask for instance @epixoip or anybody who can setup a system with at least 9 GPUs to test if this is still a problem? (I don't have a setup like this :( )

---

It could also have something to do with (lack of enough) main memory (RAM)... but this should be pretty easy to see (and idealy it should even result in an error).

**Comment by jsteube** [comment]
I just got another Idea. Can we maybe spawn a VM and just assign it like 24 CPU's? Since we now have support for CPU this could work...

**Comment by magnumripper** [comment]
Any number of CPU cores will still report as one single device (just like a GPU may have 3000 cores).

I haven't given up on VCL just yet so I will test this sooner or later.

**Comment by cryptolovi** [comment]
I did ran the above tests again on a 24+ GPU machine with hashcat (v3.00-beta-44-g5d5d1a5) linux 64 bit compiled from sources. The problem described doesn't occur anymore, even with a dictionary containing 1 entry. Both modes 6 and 7 find the hash values now.

**Comment by philsmd** [comment]
Thank you very much for the notice.

I'm sorry that I'm not able to say/pinpoint which changes/commits fixed this problem... There were too many changes we made from the opening of the original trac ticket till today.
But it shouldn't really matter (and if someone really needs to - and is able to - find the commit that fixed it, one could just checkout the different commits and see which "versions" are still affected and which aren't). The only thing that matters is that it is fixed and there is no more such (known) strange bug.

Thank you again for reporting the current state of this problem, this allows us to close this ticket (because it really wasn't that easy to test for me etc, with that many GPUs ;) )
:)

**Comment by cryptolovi** [comment]
No worries, thank you guys for such a well made product.
