### ISSUE TITLE
hashcat-deps (dependencies) should not be in /opt/ and therefore not require root permission

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#14]
Currently the dependencies for oclHashcat (and for hashcat too) are all within the /opt/ directory (/opt/hashcat-deps to be exact).

I suggest that we should move the hashcat-deps directory directly into the root path of the github clone such that no root permissions are required and that the dependencies are local to the cloned repository.

Thx

**Comment by jsteube** [comment]
Merged, thanks!
