### ISSUE TITLE
Could SL3 be re-implemented (without support nor documentation)?

### ISSUE THREAD

**Issue by crushedice2000** [hashcat/oclHashcat#17]
Hi! I know that SL3 was a great trouble for your project, however I think that it's a handy module. Could it be reimplemented? However, to avoid problems you simply could remove all the documentation/support.

**Comment by Xanadrel** [comment]
No, fuck off.

**Comment by jsteube** [comment]
@Xanadrel please fix your wording

However, SL3 is not going to be re-implemented

**Comment by 0x2b3bfa0** [comment]
Understood! Could I do a fork with SL3 support (completely unlinked -except the author and license- from this project)?

**Comment by magnumripper** [comment]
> could I do a fork with SL3 support (completely unlinked -except the author and license- from this project)?

This is a puzzling question. The only one able to answer it is you.

**Comment by crushedice2000** [comment]
@magnumripper: I refer to licensing troubles. **;-)**

**Comment by epixoip** [comment]
It's MIT license...

**Comment by crushedice2000** [comment]
@epixoip: Ok, I never knew what meant MIT license. I'm a bit lazy. Now I've read the license.txt file. If I have a bit of time I'll fork and implement. What about merging then? Will be accepted?
