### ISSUE TITLE
Removing duplicate hashes... cudaHashcat!

### ISSUE THREAD

**Issue by ngodai** [hashcat/oclHashcat#18]
hi bro,
I use cudaHashcat-v1.37 to recovery WEP,WPA. I get a problem, when i run command line:
cudaHashcat -m 2500 -a 0 myhash mydict
it worked and very strong. But when i run cudaHashcat like a service of windows, and print result to a file, i got some text like this:

cudaHashcat v1.37 starting...

Removing duplicate hashes...
Comparing hashes with potfile entries...                                       
Structuring salts for cracking task...                             
Generating bitmap tables with 16 bits...

I google it, and I tried to use other versions (v 2.0, v 1.31), the result is not change. When I use hashcat(run like a service of windows) it worked.
My system: windows 8.1, Nvidia GeForce GTX 980, driver version: 9.18.13.4762, and cuda tool.
What 's the matter, and what should i do?
Thank you so much!

**Comment by jsteube** [comment]
The issues on GitHub are for development discussions only. Please use our Forum instead:

https://hashcat.net/forum/
