### ISSUE TITLE
Half MD5 algorithm doesn't work in cudaHashcat on GTX 780 (error 999)

### ISSUE THREAD

**Issue by dmitry-zakablukov** [hashcat/oclHashcat#19]
Good day!

I wanted to launch benchmark on my GTX 780, but it failed on Half MD5 algorithm with error "ERROR: cuStreamSynchronize() 999":

```
cudaHashcat v2.01 starting in benchmark-mode...

Device #1: GeForce GTX 780, 3072MB, 1006Mhz, 12MCU

Hashtype: Half MD5
Workload: 1024 loops, 256 accel



ERROR: cuStreamSynchronize() 999
```

This error is present both in 32-bit and 64-bit versions of cudaHashcat.

May be the value of loops (1024) is too large?
My OS is Win 7 x64, 16GB RAM.

**Comment by jsteube** [comment]
Maybe, yes. Please find out by trying: -b --benchmark-mode 0 -n 1 -u 1 --runtime 30

**Comment by philsmd** [comment]
Also make sure that you did apply the timeout patch: https://hashcat.net/wiki/doku.php?id=timeout_patch

**Comment by dmitry-zakablukov** [comment]
@philsmd thank you! It helped me. Benchmark worked without any problem.
But I've thought that oclHashcat's feature is "Low resource utilization, you can still watch movies or play games while cracking". May be it is true, but in this case I don't understand why TDR stops benchmark's work. I haven't saw any message about driver hang up and/or recover.

**Comment by epixoip** [comment]
Benchmark uses the highest workload profile (-w 3). If you want low resource utilization you should use the lowest workload profile (-w 1) while actually cracking.
