### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by shellster** [hashcat/oclHashcat#27]
Is there any plans to support the ARM platform anytime soon?  More to the point, is there any major known reasons why it would be particularly hard to do?

**Comment by magnumripper** [comment]
Is that thing LE or BE as is?

**Comment by shellster** [comment]
Well, I was asking about support of ARM platforms in general.  The Jetson TK1 is LE I believe (armv7l).

In the past (possible even present), ARM hasn't ever been powerful enough to really be worth the trouble, but that is likely on the cusp of changing.

**Comment by epixoip** [comment]
This might be something to consider for the future as ARM pushes its way into the server market, but right now there's real no value in supporting ARM (not to say we would reject PRs from someone who adds ARM support, just not something we would likely focus on adding.) You're far more likely to see POWER support before ARM.

**Comment by magnumripper** [comment]
Assuming this thing runs Linux, I can't see anything needing changing at all? We already have a target for Linux (possibly assuming LE) and I see no SIMD intrinsics or assembler used anywhere.

**Comment by epixoip** [comment]
Oh, I'm sorry, for some reason I thought we were talking about Hashcat, not oclHashcat (probably because otherwise the topic makes no sense :wink:). I did indeed have NEON and AltiVec in mind when i wrote that comment. But yes you're of course correct, cross compiling oclHashcat for ARM should already be possible today.

**Comment by jsteube** [comment]
Today I got an email from an User asking for support to run the Host code on a Big Endian architecture CPU. I'm not sure if it's worth patching, especially since this requires a huge effort. Why should someone want to do this? Is there any CPU that is BE architecture and so fast that it's really useful to run oclHashcat on it?

**Comment by roycewilliams** [comment]
Maybe they have access to a large number of them?

**Comment by epixoip** [comment]
As we've discussed on IRC a couple times, POWER is potentially worth supporting. I don't know if there will be a CPU OpenCL driver (would be really sweet if there were), but at the very least Nvidia have joined the OpenPOWER consortium, so you will see affordable POWER servers with Nvidia GPUs in the near future.

**Comment by neheb** [comment]
I just compiled hashcat on android as well as an ARMv5 device. No real problems. Issue should be closed i think.

**Comment by jsteube** [comment]
Thanks for testing!

**Comment by 0xicl33n** [comment]
I just compiled hashcat on a Jetson TK1(Ubuntu 14.04)  as @shellster mentioned running hashcat on.

It compiled just fine but..

    [root@turbine[~]$hashcat --opencl-info
    hashcat (v3.10-829-g646a472) starting...

    clGetPlatformIDs(): CL_UNKNOWN_ERROR

No opencl device detected. How can i take a better look to make sure i built things correctly? Are there CFLAGS i should have used?

**Comment by jsteube** [comment]
From what I've seen the Jetson TK1 does not support OpenCL, only CUDA.
So the Error message would be OK. Not related to your compiling.

**Comment by 0xicl33n** [comment]
and my assumption is hashcat doesnt use cuda anymore?

**Comment by jsteube** [comment]
Yes, Project switched to OpenCL

**Comment by ghost** [comment]
Ported please!!

**Comment by sibero80** [comment]
@neheb , could you share any insights on the process? would love to compile it for ARM64 (LG G5)

**Comment by jsteube** [comment]
Support was added by using CUDA instead of OpenCL (if detected). Should work now. Confirmed to work on NVIDIA Jetson and IBM POWER9.
