### ISSUE TITLE
Reimplementing haschat/oclHashcat as Rumprun?

### ISSUE THREAD

**Issue by paxwareDev** [hashcat/oclHashcat#28]
First, would it be possible for the developer to make a version that runs as a [rumprun kernel](http://rumpkernel.org) for use on bare metal, or a hypervisor, and second, would it even make a difference regarding speed, etc, if it was? Just an idea.

**Comment by epixoip** [comment]
Way outside the scope of this project. If you want to work on this, go for it. But it doesn't even seem like something that would be desirable, let alone possible, for oclHashcat.

Further, these types of questions are better suited for the forums, not a Github Issue.

**Comment by jsteube** [comment]
Yeah hashcat forum should be the correct platforms for this
