### ISSUE TITLE
oclHashcat64.bin 'OPENCL_2.0' not found error

### ISSUE THREAD

**Issue by roo7break** [hashcat/oclHashcat#31]
Hi,

I have Xubuntu 14.04.3 LTS setup with AMD HD 7950. I have installed AMD driver 15.11 (http://support.amd.com/en-us/download/desktop/previous/detail?os=Linux%20x86&rev=15.11). However, when I download and run oclHashcat 2.0 or 2.01, it errors as shown below.

```./oclHashcat64.bin: /usr/lib/x86_64-linux-gnu/libOpenCL.so.1: version `OPENCL_2.0' not found (required by ./oclHashcat64.bin)```

It works for 1.37 without any issues. Can you help identify the issue?.

Thanks

**Comment by epixoip** [comment]
Looks like you have more than one libOpenCL on your system, and oclHashcat is picking up the wrong one. Should only have one libOpenCL, and that should be the one installed by AMD Catalyst. 

dpkg -l | egrep -i 'nvidia|fglrx|opencl'
find / -name libOpenCL\*

**Comment by roo7break** [comment]
Awesome. thanks to dpkg -l | egrep -i 'nvidia|fglrx|opencl' i was able to locate ocl-icd-libopencl1 as the culprit. Purged it, and oclHashcat is working beautifully.

Thanks for your help.

**Comment by kittinan** [comment]
i have same issue like @roo7break  after remove ocl-icd-libopencl1:amd64, oclHashcat work perfectly.

sudo apt-get purge ocl-icd-libopencl1:amd64

**Comment by ghost** [comment]
I also have this problem after i installed wine.

ocl-icd-libopencl:amd64 is installed along with the wine package so i cannot used wine if i remove this library.

any workaround?
