### ISSUE TITLE
Use JIT compiler for DEScrypt

### ISSUE THREAD

**Issue by jsteube** [hashcat/oclHashcat#4]
To increase DEScrypt cracking speed even more we should add a JIT compiler macro to set the salt of the hash which is to crack. This leads directly to the assumption that this technique makes only sense for single-hash cracking. Sure technically that's not correct but adding this to multi-hash, in the worst case, would create 4k of kernel code. The startup time would be horrible and the GPU memory to small. We could limit this feature to like 10 unique salts but that would make the code harder to understand. That's why i tend to implement this only for single hashes

**Comment by roycewilliams** [comment]
What is the potential performance improvement -- for single hashes, and for multiple hashes?

**Comment by magnumripper** [comment]
According to http://hashcat.net/forum/thread-4761-post-26977.html#pid26977 it's 25-30% for 290X.

I don't think the GPU memory is too small, we've run JtR like that (all 4096 kernels JIT compiled once using fake hashes, and obviously we cache them forever for re-use). The startup time for 4096 salts (even with cached kernels) is horrible though. We even experimented with threaded JIT compiles: Since `make -sj32` for a normal C build is so much faster we figured we'd see the same, but apparently it ended up serialized anyway with most vendors' drivers (when it worked at all).

**Comment by jsteube** [comment]
What about lowend GPU's? I'm not sure they could load all 4k kernels. But still interessting, how much was the startup time?

**Comment by magnumripper** [comment]
Some old notes from a contest says loading all 4096 salts in JtR took 40 minutes first time (compiling) and less than one minute after that (cached). That was on Tahiti.

Actually *having* that many salts is uncommon of course. Even Gawker was "just" 3,844 salts.

**Comment by jsteube** [comment]
While implementing I just realized that there's no JIT support yet for NV in oclHashcat. Since I always start development on AMD I never really thought about. But luckily it seems with latest CUDA SDK they added support for JIT using the CUDA driver API (not the runtime). For example there is cuLinkCreate(). I have to play with that and see if it works for what we need.

**Comment by jsteube** [comment]
This is getting annoying. So the cuLinkCreate() is not able to compile from source, only from .ptx. 

Actually there's no easy solution to compile from source as you know it from OpenCL, but with CUDA SDK v7.0 NVidia added a library NVRTC which targets this missing feature. But then, NVRTC works only on 64 bit, but not 32 bit, for some unknown reason:

> 2.1. System Requirements
> NVRTC requires the following system configuration:
> Operating System: Linux x86_64, Windows x86_64, or Mac OS X.

Another problem of this is, the user would need to install the CUDA SDK, because the library is not part of the driver distribution. OTOH, if one has installed the CUDA SDK then we can also simply call nvcc to compile from source to PTX and this will work for 32 bit and 64 bit. But run a system command to compile a kernel out of the program, how ugly is this, not to mention all the things that could possibly go wrong here. 

I'm a bit stuck here now.

**Comment by jsteube** [comment]
Pushed https://github.com/hashcat/oclHashcat/commit/968265fffb8d9f929ec18862c461031e1a7b8e83 which enables this feature for AMD. Still unknown how to proceed with NV

**Comment by jsteube** [comment]
Maybe we should really switch to OpenCL and obsolete CUDA?...

**Comment by magnumripper** [comment]
IMHO that is the way to go, sooner or later.

**Comment by jsteube** [comment]
I've decide to switch to OpenCL fully, once we did this, we can finished this enhancement

**Comment by jsteube** [comment]
Implemented :)
