### ISSUE TITLE
slight formatting problem in source code (tabs vs spaces)

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#5]
The contribution/formatting rule:
5. Uses 2-character tabs and 2-character indentations

clearly says that we should prefer 2 spaces over 1 tab. Some code parts currently do not stick to this rule. I would suggest that we fix this as soon as possible.
Thx

**Comment by magnumripper** [comment]
Clearly? I actually read it as we should use tabs, with tab width set to 2. But I noticed the existing code does not use tabs.

I'd express it as "Uses no tabs and 2-character indentations" (disregarding the fact I would persoally actually use tabs).

**Comment by jsteube** [comment]
Just to note this here, the code is -not- tab indented. It's a 2-space indention.

**Comment by jsteube** [comment]
Can you please send in a PR for this?
