### ISSUE TITLE
Build error in Archlinux with yaourt

### ISSUE THREAD

**Issue by dc3671** [hashcat/oclHashcat#62]
4.2.5-1-ARCH x86_64 GNU/Linux
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 750M] (rev a1)
Installing hashcat with yaourt results in this error.
The source url in PKGBUILD file is just this repo.
Could there be some BUG in the build file?

    ==> Extracting sources...
      -> Creating working copy of oclHashcat git repo...
    Switched to a new branch 'makepkg'
    ==> Starting pkgver()...
    fatal: No annotated tags can describe '6e680aa31c9ff0a2705452801664ce6e3d0545e3'.
    However, there were unannotated tags: try --tags.
    ==> Starting prepare()...
    Matching Makefile ...
    ==> Removing existing $pkgdir/ directory...
    ==> Starting build()...
    make: *** No rule to make target 'cudaHashcat64.bin'.  Stop.
    ==> ERROR: A failure occurred in build().
        Aborting...
    ==> ERROR: Makepkg was unable to build cudahashcat-git.

**Comment by epixoip** [comment]
Why would you open this bug report here, and not with ArchLinux?

**Comment by neheb** [comment]
This is definitely an issue with the PKGFILE not with oclHashcat. FWIW, i can compile on arch just fine.

**Comment by dc3671** [comment]
Fine, my fault.
