### ISSUE TITLE
OpenCL/OSX support

### ISSUE THREAD

**Issue by lloeki** [hashcat/oclHashcat#63]
Is this reasonable to ask? May be tied to https://github.com/hashcat/oclHashcat/issues/3

Reference: https://developer.apple.com/opencl/

**Comment by jsteube** [comment]
Sure, why not. I just hope someone can provide patches for it since I do not have an apple computer so I can't code it.

**Comment by magnumripper** [comment]
I'm extremely improductive at the moment but I'll have a look sooner or later unless someone beats me to it. The recent OpenCL changes have paved the way, should be very easy now.

Right now though, Apple's OpenCL drivers are very crappy. They were perfectly fine with JtR prior to El Capitan but now we see segfaults, incorrect results and whatnot.

**Comment by lloeki** [comment]
> They were perfectly fine with JtR prior to El Capitan but now we see segfaults, incorrect results and whatnot.

I admit I didn't write an OpenCL program myself since Mavericks, but I recently ran JtR on some Raw-SHA512-opencl task under El Cap. It was on an Intel card though, so maybe there's a flaky Nvidia or AMD driver down the line.

**Comment by magnumripper** [comment]
Sure, many combinations of formats/devices does work fine, but far from all of them. There was a major regression for El Capitan.

**Comment by lloeki** [comment]
I was merely providing a data point :-) I'll keep this in mind anyway as I may need OpenCL for other things, thanks.

**Comment by lloeki** [comment]
That's more work but maybe we can work around OpenCL: it seems Metal can be used for [GPGPU computations](http://memkite.com/blog/2014/12/15/data-parallel-programming-with-metal-and-swift-for-iphoneipad-gpu/) but I don't know how convoluted it would be to call it from C.

**Comment by matrix** [comment]
Beta is out, please test it ;)

https://hashcat.net/beta/oclHashcat-2.10b2-osx.7z

**Comment by lloeki** [comment]
Thanks @gm4tr1x. Cursory test on an Intel Iris (3GHz Core i7, Mid 2014 MBP 13"):

```
$ ./example0.sh
oclHashcat v2.10 starting...

Device #1: skipped                      
Device #2: Iris, 384/1536 MB allocatable, 1200Mhz, 40MCU

Hashes: 6494 hashes; 6494 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Applicable Optimizers:
* Zero-Byte
* Precompute-Init
* Precompute-Merkle-Demgard
* Meet-In-The-Middle
* Early-Skip
* Not-Salted
* Not-Iterated
* Single-Salt
* Raw-Hash
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 80c

Source from '/Users/lloeki/Downloads/oclHashcat-2.10/./OpenCL/m00000_a1.cl'

Device #1: Kernel /Users/lloeki/Downloads/oclHashcat-2.10/./OpenCL/m00000_a1.cl (18825 bytes)
<program source>:147:9: warning: unused variable 'tmp2'
    u32 tmp2;
        ^
<program source>:375:9: warning: unused variable 'tmp2'
    u32 tmp2;
        ^

Device #1: Kernel /Users/lloeki/Downloads/oclHashcat-2.10/./kernels/markov_le.349421b0.kernel not found in cache! Building may take a while...

------ 8< ------

Session.Name...: oclHashcat
Status.........: Exhausted
Input.Left.....: Mask (?a?a?a?a) [4]
Input.Right....: File (example.dict)
Hash.Target....: File (example0.hash)
Hash.Type......: MD5
Time.Started...: Fri Jan 15 23:05:14 2016 (13 mins, 5 secs)
Time.Estimated.: 0 secs
Speed.Dev.#1...:   164.9 MH/s
Recovered......: 2190/6494 (33.72%) Digests, 0/1 (0.00%) Salts
Recovered/Time.: CUR:30,N/A,N/A AVG:167.22,10033.42,240802.08 (Min,Hour,Day)
Progress.......: 136302297088/136302297088 (100.00%)
Rejected.......: 0/136302297088 (0.00%)

Started: Fri Jan 15 23:05:14 2016
Stopped: Fri Jan 15 23:18:22 2016
```

**Comment by matrix** [comment]
Thanks @lloeki, seems that works.

**Comment by jsteube** [comment]
Full OSX support is almost finished thanks to @gm4tr1x 

It's all in master if you want to test

**Comment by lloeki** [comment]
Built from master, and already put to good use!

Is there a timeline for the next release? I'd like to create a [Homebrew](https://github.com/Homebrew/homebrew) formula, and they require an official upstream release for a homebrew package to be built.

**Comment by Thireus** [comment]
@jsteube: Tested and working. However, performances are quite low compared to a Windows build.

Thank you for your work!

**Comment by jsteube** [comment]
@gm4tr1x can we close the issue?

**Comment by matrix** [comment]
Yes, we can
