### ISSUE TITLE
support for the Mesa compiler/driver

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#71]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | Kucikuc24 ||
| Title:                                  | OpenCL on Mesa |
| Ticket number:                  | 229 |
| Date reported:                  | 2014-01-03T01:22:04+01:00 |
| **Description**:                 |  [Please] [a]dd support for OpenCL on Mesa aside with AMD Catalyst.<br><br>Despite the fact Mesa's implementation of OpenCL currently does not support all the types of GPUs, we would be able to use oclHashcat with far more stable drivers on supported GPUs.<br><br>This could also bring some performance improvements. For more information, please see the following link:<br>[archlinux - mesa wiki](​https://wiki.archlinux.org/index.php/GPGPU#Mesa_.28Gallium.29) |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | atom       | A few days ago I checked out that resource page how the progress is going. There's not much going on there. It seems to work for some ancient cards but for current state of the art hardware the status is set to work-in-progress. I will check again in a few months. |
| 2.                               | atom       | I'll not accept this as a form of "ok we will add it" more to have it in my list so that I keep an eye on it. |
| 3.                               | Kucikuc24       | May I have a question, atom ? Did you try an actual crypto code on mesa ? I mean, pyrit should work well. The tested card in the example on Arch Wiki is from Radeon HD 6700 serie but unfortunately, I do not have such a hardware right now so I could not test it. |

**Comment by jsteube** [comment]
Update: With latest versoin from GIT we opened oclHashcat in a way that all OpenCL compatible platforms should be able to work. Maybe this does work now, someone needs to test

**Comment by neheb** [comment]
http://pastebin.com/M9F0MdZf

can't compile a kernel. no idea if it works otherwise.

**Comment by neheb** [comment]
error changed with the latest code a while back to
ERROR: clGetDeviceInfo() : -30 : CL_INVALID_VALUE

**Comment by kenshin33** [comment]
ERROR: clGetDeviceInfo() : param (4043) : -30 : CL_INVALID_VALUE
I added something to get the param_name in my case it was 0X4043
which seems to be an AMD thing.
https://www.khronos.org/registry/cl/extensions/amd/cl_amd_device_attribute_query.txt

there's no mention of this in any header in /usr/include/CL/*

**Comment by neheb** [comment]
oh so CL_DEVICE_WAVEFRONT_WIDTH_AMD is unimplemented in Mesa? Hmm commenting that out and letting the build proceed results in a bunch of error: OpenCL does not support the 'static' storage class specifier

At least that's progress!

**Comment by neheb** [comment]
types_ocl.c needs "#pragma OPENCL EXTENSION cl_clang_storage_class_specifiers : enable" so that the kernels compile. Unfortunately, after that they all crash. Needs investigating.

**Comment by neheb** [comment]
alright, three issues left: 

CL_DEVICE_WAVEFRONT_WIDTH_AMD is not implemented and as such, some workaround is needed to get the device processor cores. 

second is that this needs to be tested. I believe Southern and Volcanic Island GPUs are supported. Evergreen and Northern islands are missing global atomics. Forget about earlier.

Third issue is that oclHashcat complains that an unsupported version of Catalyst is used. The check should be used for less than HD7000 series I believe.

Also, assembly optimizations for amd_bit/bytealign and amd_bfe should be researched as those are unimplemented. I imagine it would be slow.

**Comment by jsteube** [comment]
I've patched those cases and for GCN and newer, MESA is now fully supported. And you're right, It's much slower than catalyst because of missing rotate() and bitselect(). Anyway that's beyond our scope. If they decide to map it to the hardware instruction we will automatically make use of it anyway.
