### ISSUE TITLE
support for Kerberos 5 AP-REQ

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#81]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | initnull |
| Title:                                  | Kerberos 5 AP-REQ |
| Ticket number:                  | 524 |
| Date reported:                  | 2014-10-16T04:35:46+02:00 |
| **Description**:                 |  Hi,<br>Could it be possible to add support for AP-Request Kerberos V5 hash? Currently, oclHashcat supports only the AS-Request Type 1 (https://hashcat.net/trac/ticket/137)<br><br>As defined in:​ http://ftp.samba.org/pub/samba/specs/draft-brezak-win2k-krb-rc4-hmac-02.txt<br><br>T = 1 for TS-ENC-TS in the AS-Request<br>T = 2 for the Server Ticket in the AP-Request<br>This T is used in the creation of K1<br><br>This particular type is used in the silver ticket attack. Basically it's pretty much the same with a twist on K1. The following code comes from ​https://github.com/nidem/kerberoast with some modifications to makes it easier to explain.<br><br>word is the password plaintext = "Oksala123"<br>key is ntlm of password in utf-16le format<br><br><br>key = ntlmhash(word)<br>def ntlmhash(s):<br>hash = hashlib.new('md4', s.encode('utf-16le')).digest()<br>return hash<br><br><br>messagetype is 2 (AP-Request T)<br>edata is<br>binascii.unhexlify('3be794d602ed567c5fcd1b4cee7eb0653864faafef433c99b49c83fba4b6b33ff24312596347d7b9b1a30d36606987caef3e9198659fbbc08ddac9fb6b80ef167ccfebe09ec71973695675438a53ee1cdae29601f423dea0b223c1fccc05d841e7a02144e3a35b56c09609df000e74b165ae6eea7fc12b9919a54c0070dc8555b1c228b45089be24648b20dbef720ac71ef4a4bd3808a8489adae7fe6e3f2663e881ad57033e91583fdca5b2db96de53192a381654d83d489fb292826118564fa0ef7901fc25deda154978e5b15f23fb11038a46f2d478c31c11aa7f6e02a66de6ce3b5079fdf9cd76861d56bc70a4eb4c0ebbceac383fd5b0545070d9c7a33b9a45cbed4314f28cbaea345a1d834b46a05f67eb8114da7140b9365dec429967d20aa864853579b61a0f581ae9e7570c94351edc6b5e74585d2ce0640fe7a5704e6dad5431e975ab7800bd03a01226c77c12e01c647500a682ebc465df6cff7086a580e2abfc195fbf3516e53ac1ff9d99240226715e5885a5c57b0722d0c807fbe6df27d2a00b8f2e6e7e6263ea73fe10b4ce74bbc54eb620f89dc34d8348289d0bea42dfe10c0b821f7dba10455dfe3abe48f1ca5ac9ce45d4b3641749ed66fe5bfe7a57f267fd3d1841aae466214cc719cb58b4fe8ac2ed42c77cc905273ad7316efb5c119fcfc6cebf87149646e4c220527fd3a4c9a03de296f03eccee17f90dc2523805adf2f1c60afcfb575608362c0df24b15445eb08f1ea795f3e482a333a6a63b83d4def63cc2f6c9d10d46a05a82bc7b2d6524ef2560f50f902ecb0cb586376b2af4c16547d4b30ec2c239d6d625edf375d1067e8f8b057a865b88d63399cf136d3c2628f9fc695c298f99f1e61d3ed427c1434c9da4de069c24aa1ad3912744a0002b8f2596bc56a91a80970012ef5064c99af082e3494e2f6d37597cc62522503811c31446d6447d7286a1820f6bf99cc28166cbbac3174138ed1830aa6b312ad2b277f059635d52f6d3b20109d65d5b725f49a306ebc347df39628b443c3fcc1f564d31ddde0efaad4434500c6428575df45f84549a884b08c6aca82d9d06c903cca44c38516d15a43c3b0482f098351b783bed14a3a18c91efda24328453c65aad96da81557db1242650757f5ab95c23a1bcd87f496344f7225a5e36f9bc5e0f77f18891d8360acf805b3c71cf78ac6ac79c527ab29493c35c41409cb28d14c16db1ba2b6a775461a1defd783c1acbb295ba6bd31a7b4d4bb6991e2e9a1b6c740f3175cbdd3d9fb8c5bf250e39b3caf558d32d4e4ebbc6732486004657581f74d5af8293ec16baffe27ceb54cef29d2c21732b18ce297a4582fb5fcffe92ce4ff469b835075f1867c3ac140ffc44802634eb33543fe1cb887dec5d84718502a3bb0eecec2a0c154370555b5627420ee8fff83021a6a43a788747e6f43c48e605cddbf6dc31c8f8bc95f79f43d865677ecaeb71f738d496f797cd06975c1438f5575b6442980a1c31b5d5d0a31356fab640301a8089141b529e9fd01069')<br><br>def decrypt(key, messagetype, edata):<br>K1 = hmac.new(key, chr(messagetype) + "\x00\x00\x00", hashlib.md5).digest()<br>K2 = K1<br>K3 = hmac.new(K1, edata[:16], hashlib.md5).digest()<br>ddata = rc4crypt(K3, edata[16:])<br>checksum = hmac.new(K2, ddata, hashlib.md5).digest()<br><br>if checksum == edata[:16]:<br>return ddata[8:], ddata[:8]<br><br>if the first ddata[8:] is not none, we have a successful decryption.<br><br>Now, im pretty sure we can cut the checksum part as you did in the AS-REQ version, the decrypted data of this big chunk also starts with<br>20141015171431Z<br><br>Im joining you the original file extracted from kerberos::list /export with mimikatz. it can be loaded with kerberoast (link in the begining). The password is Oksala123<br><br>Thanks. |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | atom       | I agree there's some cracking speed optimization potential by not using the checksum [but by using] the 20141015171431Z timestamp [instead].  |
| 2.                               | twi1ight        | wow, somebody already reported this type, it would be great in pentesting active directory  |
| 3.                               | monoxgas        | Up one for including this type. Should be a really easy change from the AS-REQ type.  |

**Comment by philsmd** [comment]
[a.zip](https://github.com/hashcat/oclHashcat/files/83070/a.zip)

**Comment by Fist0urs** [comment]
What kind of help do you need for this one? Details on algorithm or some more hands to code it?

**Comment by magnumripper** [comment]
I whipped up a JtR plug today but didn't commit it yet: We should agree on an input format to use so we don't end up different. kirbi2john.py currently outputs this from the attached file:

```
$ ./kirbi2john.py 1-40a00000-gtremblay@http~WIN-SS.ettic.ca~80-ETTIC.CA.kirbi 
$krb5tgs$unkown:3be794d602ed567c5fcd1b4cee7eb065$3864faafef433c99b49c83fba4b6b33ff24312596347d7b9b1a30d36606987caef3e9198659fbbc08ddac9fb6b80ef167ccfebe09ec71973695675438a53ee1cdae29601f423dea0b223c1fccc05d841e7a02144e3a35b56c09609df000e74b165ae6eea7fc12b9919a54c0070dc8555b1c228b45089be24648b20dbef720ac71ef4a4bd3808a8489adae7fe6e3f2663e881ad57033e91583fdca5b2db96de53192a381654d83d489fb292826118564fa0ef7901fc25deda154978e5b15f23fb11038a46f2d478c31c11aa7f6e02a66de6ce3b5079fdf9cd76861d56bc70a4eb4c0ebbceac383fd5b0545070d9c7a33b9a45cbed4314f28cbaea345a1d834b46a05f67eb8114da7140b9365dec429967d20aa864853579b61a0f581ae9e7570c94351edc6b5e74585d2ce0640fe7a5704e6dad5431e975ab7800bd03a01226c77c12e01c647500a682ebc465df6cff7086a580e2abfc195fbf3516e53ac1ff9d99240226715e5885a5c57b0722d0c807fbe6df27d2a00b8f2e6e7e6263ea73fe10b4ce74bbc54eb620f89dc34d8348289d0bea42dfe10c0b821f7dba10455dfe3abe48f1ca5ac9ce45d4b3641749ed66fe5bfe7a57f267fd3d1841aae466214cc719cb58b4fe8ac2ed42c77cc905273ad7316efb5c119fcfc6cebf87149646e4c220527fd3a4c9a03de296f03eccee17f90dc2523805adf2f1c60afcfb575608362c0df24b15445eb08f1ea795f3e482a333a6a63b83d4def63cc2f6c9d10d46a05a82bc7b2d6524ef2560f50f902ecb0cb586376b2af4c16547d4b30ec2c239d6d625edf375d1067e8f8b057a865b88d63399cf136d3c2628f9fc695c298f99f1e61d3ed427c1434c9da4de069c24aa1ad3912744a0002b8f2596bc56a91a80970012ef5064c99af082e3494e2f6d37597cc62522503811c31446d6447d7286a1820f6bf99cc28166cbbac3174138ed1830aa6b312ad2b277f059635d52f6d3b20109d65d5b725f49a306ebc347df39628b443c3fcc1f564d31ddde0efaad4434500c6428575df45f84549a884b08c6aca82d9d06c903cca44c38516d15a43c3b0482f098351b783bed14a3a18c91efda24328453c65aad96da81557db1242650757f5ab95c23a1bcd87f496344f7225a5e36f9bc5e0f77f18891d8360acf805b3c71cf78ac6ac79c527ab29493c35c41409cb28d14c16db1ba2b6a775461a1defd783c1acbb295ba6bd31a7b4d4bb6991e2e9a1b6c740f3175cbdd3d9fb8c5bf250e39b3caf558d32d4e4ebbc6732486004657581f74d5af8293ec16baffe27ceb54cef29d2c21732b18ce297a4582fb5fcffe92ce4ff469b835075f1867c3ac140ffc44802634eb33543fe1cb887dec5d84718502a3bb0eecec2a0c154370555b5627420ee8fff83021a6a43a788747e6f43c48e605cddbf6dc31c8f8bc95f79f43d865677ecaeb71f738d496f797cd06975c1438f5575b6442980a1c31b5d5d0a31356fab640301a8089141b529e9fd01069
```

This is problematic in that it includes a `:`. Also, it puts checksum first and separated by `$` from the other data. I don't mind that but it differs from krb5pa$23$.

Right now my format use this instead (mimicing krb5pa$23$):

```
$krb5tgs$23$$$$3864faafef433c99b49c83fba4b6b33ff24312596347d7b9b1a30d36606987caef3e9198659fbbc08ddac9fb6b80ef167ccfebe09ec71973695675438a53ee1cdae29601f423dea0b223c1fccc05d841e7a02144e3a35b56c09609df000e74b165ae6eea7fc12b9919a54c0070dc8555b1c228b45089be24648b20dbef720ac71ef4a4bd3808a8489adae7fe6e3f2663e881ad57033e91583fdca5b2db96de53192a381654d83d489fb292826118564fa0ef7901fc25deda154978e5b15f23fb11038a46f2d478c31c11aa7f6e02a66de6ce3b5079fdf9cd76861d56bc70a4eb4c0ebbceac383fd5b0545070d9c7a33b9a45cbed4314f28cbaea345a1d834b46a05f67eb8114da7140b9365dec429967d20aa864853579b61a0f581ae9e7570c94351edc6b5e74585d2ce0640fe7a5704e6dad5431e975ab7800bd03a01226c77c12e01c647500a682ebc465df6cff7086a580e2abfc195fbf3516e53ac1ff9d99240226715e5885a5c57b0722d0c807fbe6df27d2a00b8f2e6e7e6263ea73fe10b4ce74bbc54eb620f89dc34d8348289d0bea42dfe10c0b821f7dba10455dfe3abe48f1ca5ac9ce45d4b3641749ed66fe5bfe7a57f267fd3d1841aae466214cc719cb58b4fe8ac2ed42c77cc905273ad7316efb5c119fcfc6cebf87149646e4c220527fd3a4c9a03de296f03eccee17f90dc2523805adf2f1c60afcfb575608362c0df24b15445eb08f1ea795f3e482a333a6a63b83d4def63cc2f6c9d10d46a05a82bc7b2d6524ef2560f50f902ecb0cb586376b2af4c16547d4b30ec2c239d6d625edf375d1067e8f8b057a865b88d63399cf136d3c2628f9fc695c298f99f1e61d3ed427c1434c9da4de069c24aa1ad3912744a0002b8f2596bc56a91a80970012ef5064c99af082e3494e2f6d37597cc62522503811c31446d6447d7286a1820f6bf99cc28166cbbac3174138ed1830aa6b312ad2b277f059635d52f6d3b20109d65d5b725f49a306ebc347df39628b443c3fcc1f564d31ddde0efaad4434500c6428575df45f84549a884b08c6aca82d9d06c903cca44c38516d15a43c3b0482f098351b783bed14a3a18c91efda24328453c65aad96da81557db1242650757f5ab95c23a1bcd87f496344f7225a5e36f9bc5e0f77f18891d8360acf805b3c71cf78ac6ac79c527ab29493c35c41409cb28d14c16db1ba2b6a775461a1defd783c1acbb295ba6bd31a7b4d4bb6991e2e9a1b6c740f3175cbdd3d9fb8c5bf250e39b3caf558d32d4e4ebbc6732486004657581f74d5af8293ec16baffe27ceb54cef29d2c21732b18ce297a4582fb5fcffe92ce4ff469b835075f1867c3ac140ffc44802634eb33543fe1cb887dec5d84718502a3bb0eecec2a0c154370555b5627420ee8fff83021a6a43a788747e6f43c48e605cddbf6dc31c8f8bc95f79f43d865677ecaeb71f738d496f797cd06975c1438f5575b6442980a1c31b5d5d0a31356fab640301a8089141b529e9fd010693be794d602ed567c5fcd1b4cee7eb065
```

(checksum now at the end, without any separator)

Another thing I'd need to know is whether the data portion (1076 bytes in this sample) can be smaller/larger? And if so, what is the maximum?

**Comment by Fist0urs** [comment]
@magnumripper 

Well kirbi2john relies on tickets created by one of the tools part of mimikatz suite, which requires to extract TGT from LSASS memory. So this parser is only for Windows oriented RC4 encrypted TGS whereas it is possible to have some using Linux (eg. using Samba).

That said, I think we shouldn't rely on a particular output format from one specific script but get a a common format, as you mentionned.

To answer your other question, size of encrypted data can vary (but I guess we can easily fix an upper bound as encrypted-fields should contains strings like domain name, SPN, etc. which are not supposed to be that long...).

**Comment by gentilkiwi** [comment]
`RC4_HMAC_NT` is much used in UNIX world too ;)
I would recommend to support:
- `DES_CBC_MD5` (3) -- the only one supported by all, but deprecated
- `RC4_HMAC_NT` (23)
- `AES128_CTS_HMAC_SHA1_96` (17)
- `AES256_CTS_HMAC_SHA1_96` (18)

By the way, "kirbi" files are not really `mimikatz` related, it's the standard ASN.1 for KrbCred from RFC. And if you support extracting from "kirbi", it will be easy to support extracting from network capture too ;)

I'm fan of your work guys :bowtie: !

**Comment by Fist0urs** [comment]
> RC4_HMAC_NT is much used in UNIX world too ;)

I was actually talking about kirbi2john parser, not the type of algorithm used :)

> DES_CBC_MD5 (3) -- the only one supported by all, but deprecated

This one is disabled by default, but if for an odd reason it was re-enabled, this could be an option yes (also, are you sure this one is still supported on Windows Server 2012?)

**Comment by gentilkiwi** [comment]
_Sure_: **not** :)
But I often "find" keys in memory for this algorithm ;)

**Comment by Fist0urs** [comment]
Well, they are automaticaly generated, either on workstation and DC, as AES ones, that is by design iirc. But using them or not is defined by DC, so I guess you got reject while try to authenticate even if you declare supporting only this algorithm.

Anyway, that's not the subject. Concerning AES, we could try to implement this ones too, but I don't know if this worths as this would be extremely slow and hard to implement using SIMD...

**Comment by magnumripper** [comment]
The best way to support this and other algorithms is to supply more samples! Ideally several per algorithm and from different networks and always with a known password of course.

Oh, and I've got another question (as long I only got the one sample a.zip attached above): I found the known plaintext 20............Z starting at `cleartext[107]` (while krb5pa has it at `cleartext[14]`). The latter is a fixed position but given only one sample I'm not 100% sure this one is? If it isn't, it probably will be faster not bothering with the known-plain optimization.

**Comment by magnumripper** [comment]
> Concerning AES, we could try to implement this ones too, but I don't know if this worths as this would be extremely slow and hard to implement using SIMD

Vectorized RC4 is also impossible to implement. But it's not a problem since it's so fast anyway and you can do parts of an algo vectorized and parts of it with scalar code.

**Comment by Fist0urs** [comment]
> The best way to support this and other algorithms is to supply more samples! Ideally several per algorithm and from different networks and always with a known password of course.

I'll provide you some :)

> Vectorized RC4 is also impossible to implement. But it's not a problem since it's so fast anyway and you can do parts of an algo vectorized and parts of it with scalar code.

Yes of course.

Concerning the feasability of actually cracking "real-cases" ciphers, fyi targeted ciphers are from accounts where a Service Principal Name (SPN) is given. These accounts are normally services accounts ie. random passwords... But when using an application requiring this type of account, sometimes Administrators provide user account, so a maybe non-random password... That's what interests us.
I'll generate some user accounts like that for you, trying to make ciphered parts as long as possible :)

**Comment by Fist0urs** [comment]
> Oh, and I've got another question (as long I only got the one sample a.zip attached above): I found the known plaintext 20............Z starting at cleartext[107](while krb5pa has it at cleartext[14]). The latter is a fixed position but given only one sample I'm not 100% sure this one is? If it isn't, it probably will be faster not bothering with the known-plain optimization.

I'll try to generate some samples to check that, but I don't think there are some fixed position, even on pre-authentication case (I am not sure, I'll take a look).

**Comment by magnumripper** [comment]
@Fist0urs made me aware there is already a krb5tgs format in JtR (I didn't know/remember that). But that format is untagged, just `<hex checksum>$<hex data>`. I still think we should add some tag like `krb5tgs$23$`at minimum. Besides, the $23$ is relevant, isn't it? If we implement the other algos they will have other numbers, right?

**Comment by Fist0urs** [comment]
Yes, 23 is the constant that specifies that RC4_HMAC_NT is used. This could indeed be the tag we are searching for, to identify the format (as DES_CBC_MD5 would be 3).

Fyi, "AP-Req" is the name of the process which consists in relaying a TGS ticket to the server which hosts the service we want to authenticate to. This TGS ticket is the result of the "TGS-Rep" obtained after doing a "TGS-Req" to the KDC.

That's why there is a bit of confusion AP-Req/TGS-Rep but they are the same tickets :)

**Comment by magnumripper** [comment]
FYI it turns out we've had reports (https://github.com/magnumripper/JohnTheRipper/issues/1838) that max size of eadata should be at least 20480.

Also, the "known plain" trick is unfeasible because the timestamp's offset does vary. I guess doing some variant of `memmem()` would be slower than just always doing a complete calculation.

**Comment by Fist0urs** [comment]
@magnumripper 

Actually, I think I found a way to get rid of the max size of edata, so as to the last hmac_md5 operation and get a known plain attack

**Comment by jsteube** [comment]
Done with https://github.com/hashcat/oclHashcat/pull/225

**Comment by gabtremblay** [comment]
Just wanted to say thanks. I was the initial reporter.

**Comment by Fist0urs** [comment]
My pleasure :). I actually needed this one too!

**Comment by edermi** [comment]
Just a short question: Has `AES256_CTS_HMAC_SHA1_96` (Type 18) been implemented as suggested by @gentilkiwi? John Jumbo supports them.

**Comment by Fist0urs** [comment]
Yup it will be, when I have time ;)
