### ISSUE TITLE
support to run oclHashcat within a cygwin shell

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#82]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | Mangix |
| Title:                                  | Cygwin support? |
| Ticket number:                  | 535 |
| Date reported:                  | 2014-11-17T02:53:20+01:00 |
| **Description**:                 |  currently, oclHashcat does not work properly with cygwin. All of the commands (s, q, p, etc.) do not get sent to the oclHashcat application. Instead, when using CTRL + C to exit it, the commands get sent separately.<br><br>Would be useful to have it work correctly as cygwin supports openssh as a server(SSHing to your Windows box) as well as screen to manage oclHashcat. |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | philsmd       | The main problem here is that the windows binaries of oclHashcat are meant to work great with cmd (the windows default command prompt).<br>There are 2 features that oclHashcat implements within the status line:<br>- user does not see the key that he presses (input will not be echoed)<br>- user does not need to press ENTER after each key he presses for oclHashcat to recognize it<br><br>exactly those 2 features are somehow platform-dependent (linux and windows treat this input differently).<br><br>Since you now use cygwin on a windows machine, we indeed somehow need to have the linux-behaviour but the main problem is that the compiler for the windows binaries does not support the linux-behaviour (and as you can guess, devs do not use some sort of cygwin compiler at the moment).<br><br>On the other hand, even if you are on cygwin, the remaining part needs to work like on a normal windows system (of course the underlying operating system is still windows after all).<br><br>I can think of a compromise which would somehow work, but it unfortunately doesn't work great (and above all is doesn't work like the native windows and native linux status prompt of oclHashcat):<br><br>- oclHashcat will detect if cygwin is running<br>- if cygwin will be detected and the user inputs a key it will be echoed<br>- if cygwin will be detected and the user inputs a key he needs to also press ENTER after each and every key<br><br>The last 2 points of course aren't that great, but currently I cannot come up with an acceptable solution for this problem(s) (linux-behaviour-with-windows-compiler-targeted-for-windows-system).<br><br>What do you think of my proposed solution? |

**Comment by neheb** [comment]
Oh my old issue that i completely forgot about. The problem is now that I've completely migrated to Linux and do not use Windows anywhere(good riddance). On the other hand since oclHashcat is now open source, this is probably not an issue any longer. If oclHashcat uses __WIN32__ to detect MinGW, then Cygwin(or maybe even MSYS2) should work fine since it does not define it. Well, I can't say I care really. Thinking of just closing this.

**Comment by jsteube** [comment]
@neheb Is that somehow related to your patch?

**Comment by neheb** [comment]
Oh this. Not exactly. When i originally posted it I used cygwin's sshd to ssh in to a windows computer and use screen to manage hashcat. I no longer do that but the issue where pressing keys does nothing remains. I have a feeling that it has to do with the way the windows shell interacts with hashcat vs. cygwin's bash.

**Comment by jsteube** [comment]
I tested latest hashcat v3.00 inside a cygwin shell and it seems to work fine. OP : please reopen if it's not working for you

**Comment by neheb** [comment]
works but pressing s does nothing. here's some pastebin to see the issue: http://pastebin.com/56KYZVRg

notice the row of s at the end. that was me pressing it.

edit: i think the proper solution would be a native cygwin build. i feel that the issue is with the cygwin/win32 translation layer. a few things block that though:

opencl libraries need to be loaded the windows way(ie not by using a linux style opencl icd loader).

building fails with shared.h i believe. there are a few functions that are not implemented.

**Comment by jsteube** [comment]
OK, i see. Well in that case there's no way without a true cygwin makefile target in order to set the macros to use the posix way of doing handling the user input.

**Comment by Fist0urs** [comment]
Actually this is not a trivial problem and both cygwin and msys2 have the problem when one wants to use hashcat through an ssh session (they both rely on mintty which does not adresses the problem).

After many things tried (bash on Windows, OpenSSH on Windows by Microsoft Powershell team, etc.), I found a good solution:

https://github.com/rprichard/winpty

This binary adresses the actual problems among others (unbuffered problematics and tty communications).

All you have to do is compile it on your cygwin§msys2 plateform and launch problematics binaries through this PE as follows:

`winpty ./hashcat64.exe -m ...`

**Prerequisites if you are using cygwin:**
- mingw64-i686-gcc-g++ or mingw64-x86_64-gcc-g++
- gcc-g++
- make

**Prerequisites if you are using msys2:**
- msys/gcc
- mingw32/mingw-w64-i686-gcc or mingw64/mingw-w64-x86_64-gcc
- make

Then:
`./configure && make && make install`
