### ISSUE TITLE
--keyspace  should not require valid OpenCL runtime environment

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#84]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | epixoip |
| Title:                                  | `keyspace' flag should not require valid OpenCL runtime environment |
| Ticket number:                  | 562 |
| Date reported:                  | 2015-01-26T20:39:39+01:00 |
| **Description**:                 | I would like to propose that when using [the] \`keyspace' flag, oclHashcat should simply calculate & print the keyspace, then exit. No OpenCL checks or device enumeration should be performed, as OpenCL runtime & devices are not required for this functionality.<br><br>The purpose for this request is three-fold:<br>- Reduce the overall runtime of oclHashcat when --keyspace is used. This helps reduce overhead when calling oclHaschat programmatically in a distributed environment. Presently, running `oclHashcat --keyspace' takes about 3 seconds on a system with eight GPUs. Ideally this operation should complete in milliseconds.<br>- Enable the keyspace flag to be used on systems without GPUs or an OpenCL runtime environment.<br>- Eliminate the need for the standalone keyspace binary in hashcat-utils, which is now out of date due to the refactoring in 1.32  |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | atom       | That might be possible, but it's not so easy. For example, for oclHashcat you will need at least the libOpenCL.so/.dll with correct exports otherwise it won't start. You may can replace it with a dummy library.<br><br>However, the standalone keyspace binary in hashcat-utils should be in sync with the current version. If not, we better patch it. Do you have an example [to] reproduce [it]?  |

**Comment by jsteube** [comment]
Done with latest beta version
