### ISSUE TITLE
support for samsung full disk encryption (DEK)

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#86]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | dummys |
| Title:                                  | Add Samsung full disk encryption cracking for DEK file |
| Ticket number:                  | 575  |
| Date reported:                  | 2015-02-10T21:57:19+01:00 |
| **Description**:                 |  Hello folks,<br>It could be cool [if you] implement the FDE algorithm from samsung.<br><br>It's already done by Laszlo Toh for [jtr (plugin)](https://github.com/donctl/sandy/blob/master/jtr_plugin/sandcrypt_fmt_plug.c)<br>I think it's better to read the code, I'm to[o] bad to explain crypto.<br><br>Here you have the explanation how to get the DEK -> [forensicswiki - Android full disk encryption](​http://www.forensicswiki.org/wiki/How_To_Decrypt_Android_Full_Disk_Encryption)<br><br>here the source: ​[soonerorlater.hu - DerbyCon2013](http://soonerorlater.hu/download/They_thinked_differently_DerbyCon2013.pdf)<br><br>Here is a test hash:<br>f1da84cf0f8230b9a7bc16d4bced2220436d7cb750aaa3f26f41d32848cc630d1030<br>ae35b6e373b25c1c61dd3480078967342e47236820acdfcf413a100c2df4189e50<br>a04709ca5c901d42848a48627c<br>password is test123 |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | atom       | Looks interes[~~s~~]ting. Is there still need for the algorithm? I mean because with newer Android versions [very much has changed and therefore it might be very different now] |

**Comment by jsteube** [comment]
Added with https://github.com/hashcat/oclHashcat/commit/332b3c35e5b7023a681a3b42a296bc423077ff5d

Please test

**Comment by dummys** [comment]
Hello, I've tested the one I gave to you before and it's working. I will setup my android to create new one and test again.
Thanks for this feature.
You guy rocks !

**Comment by jsteube** [comment]
yw :)
