### ISSUE TITLE
support to recover KeePass kmdx passwords

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#92]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | greenline |
| Title:                                  | KeePass kmdx |
| Ticket number:                  | 623 |
| Date reported:                  | 2015-05-14T12:47:06+02:00 |
| **Description**:                 | [Could] you [please] add [this] algorithm? To Crack KeePass database?  |

**Comment by philsmd** [comment]
Can anybody please provide some example hashes and detailed information about the scheme used? We need more info to implement this.

**Comment by homes32** [comment]
http://keepass.info/help/base/security.html
is a good place to start as it explains exactly how the 256-bit key for the block cipher is generated.

**Comment by jsteube** [comment]
implemented :)
