### ISSUE TITLE
proposed status display change for WPA(2) MAC addresses

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#94]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | Hash-IT |
| Title:                                  | WPA MAC Display Modification |
| Ticket number:                  | 629 |
| Date reported:                  | 2015-06-17T20:23:12+02:00 |
| **Description**:                 |  Just a cosmetic request for WPA Cracking. :)<br><br>Would it be possible to switch the way oclhashcat displays the AP MAC and client MAC please ?<br><br>Currently oclhashcat displays..<br>Hash.Target....: AP ESSID (Client MAC \<-\> AP MAC)<br><br>The above may lead the user to believe the MAC address closest to the AP ESSID is actually the AP's MAC, which is understandable.<br><br>I have struggled to remember the switch-around all the time I have used oclhashcat, then I thought others may also be confused, so I decided to make this request.<br><br>Could the display be more intuitive please ? Like the following...<br>Hash.Target....: AP ESSID (AP MAC \<-\> Client MAC)<br>Or better still...<br>Hash.Target....: AP ESSID (AP MAC \<-\> Client MAC) Client<br><br>Thank you. |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | philsmd       |  The main question is: can we say that variant 1 is more correct than variant 2[?]<br><br>Yes, it is a cosmetic fix and we should consider it as such.<br>But you can also think like that, from left to right:<br>- the most important info is on the left i.e. the network (name) where...<br>- the client (the second most important info, the main actor) connects to with his specific Client MAC which is (currently) in communication with<br>- the access point that in this case can be identified by the AP MAC<br><br>You can see it from many perspectives and I'm not sure if something would be more clear by just swapping the 2 addresses.<br><br>In theory, some wireless standards say that the essid and bssid do not need to be 1:1, i.e. we can have several access points with different mac addresses (which is often the case) but with the same network name (ssid). Still, that doesn't mean anything for us. We have always exactly 2 addresses and therefore 2 ways of "sorting" them is possible.<br><br>I agree that it could also be displayed the other way around i.e. AP ESSID, AP MAC, Client MAC, but I'm not sure if it should be considered as a real problem for devs to change it. Instead, there could be several drawbacks/problems that could arise when devs change it:<br><br>- the most important: some users could wonder why a new version of hashcat/oclHashcat suddenly "wrongly" displays the MACs (e.g. swapped)<br>- the output of cracked hashes also need to be changed (otherwise it would be even more confusing)<br>- the format in which the hashes are written to the outfile / potfile must be changed too<br>- pot file reading must be changed (oclHashcat reads the .pot file when started to find out if the network was already cracked)<br>- intense testing must be done, for instance to see that .hccap file is still read/written correctly (and not in a swapped manner)<br>- some 3th party wrappers may fail too and need to also implement the changes/update<br><br>and there might be even more complications than those that came to my mind.<br><br>That said, maybe there are some additional arguments that help us to convince the devs to implement this "cosmetic" fix. I'm sure that we can discuss this further, maybe also other users have some opinions against or in favor of this change.<br><br>Thx |
| 2. | Hash-IT |  Thank you for your reply.<br><br>Hmm... I see your list 1 - 6 of potential issues, I wrongly assumed this would be a simple status display modification. If it is too complicated to implement, then I guess it is not fair of me to ask for it.<br><br>The only argument I can offer is to prevent me, or others, from making further identification mistakes. Many times I still forget to switch the ESSID / MAC around in my head. It would certainly help where groups of people are working on one capture. It seems common for some testers to refer to the MAC of the AP rather than the ESSID. I noticed while helping in one of these multiple tester groups that many were actually referring to the client MAC to crack and not actually the AP MAC. Presumably this is because the MAC of the client is written next to the ESSID.<br><br>The confusion starts when some of the people know to switch the MACS around in their head and others do not.<br><br>Many penetration testers look on our hashkiller forum for the default / likely key-space for a given network. The tester may accidentally be searching for the manufacturer of the client wifi (dongle) and not the actual AP if they forget to switch them round. If the ESSID has been changed by the owner, but the password has not, then it could result in a tester incorrectly checking the keyspace for NETGEAR routers on a Virgin AP because the client used a NETGEAR wifi adaptor.<br><br>As you have kindly listed all the possible problems with altering the display and it would seem I am the only person who has mentioned it as an issue, I totally understand my request has a VERY low priority.<br><br>All I ask is you please bear it in mind and perhaps if you make other alterations to oclhashcat which may enable you to slip this request in with little additional effort, I would be very grateful if you would.<br><br>Thank you for your time and full explanation. |

**Comment by philsmd** [comment]
I would like to suggest that we close this ticket because in my opinion there is no clear benefit of switching the 2 MAC addresses. If anything, we could/should make it more clear in the wiki what the 2 MAC addresses + SSID are.
What do you think?

**Comment by neheb** [comment]
The main issue probably arises from other tools that display AP MACs first and clients after. airodump-ng is the best example. This is just cosmetic though. Might as well just close it.

**Comment by jsteube** [comment]
I agree to @philsmd here. I don't see a clear benefit of switching. Please reopen if you strongly believe we need to change this.
