### ISSUE TITLE
add an option to set a path to the .pot file

### ISSUE THREAD

**Issue by philsmd** [hashcat/oclHashcat#99]
This feature request was originally reported on the (now obsolete and offline) **trac** ticketing system of hashcat.net.

---

| Ticket details:                    |               |
| -------------------------------- | ---------- |
| Original reporter (OP):      | Wolfman |
| Title:                                  | Feature request: Option to set the potfile name. |
| Ticket number:                  | 637 |
| Date reported:                  | 2015-07-10T16:27:57+02:00 |
| **Description**:                 |  When using sessions the name of the potfile is set to the same as the session name by default. But unlike most other options (induction-dir/outfile-check) there is no way of setting a custom name. I suggest adding a parameter like --pot-name=<br><br>Having to use different potfiles for each session seems ineffective. Now you lose the advantage of easy pickings during start up.<br><br>Adding this will make the options more consistent and add a lot more flexibility when using sessions. |

---

| Comments:               |                |               |
| -------------------------- | ----------- | ---------- |
| 1.                               | roebuck       |  I agree that this feature would make the use of sessions better and more useful.<br><br>If you add a new session name , then already found hashes will not be found since the old pot is not used. If you use the same session name as before then your pot is used, but the old session is lost/overwritten. These facts make the session feature of limited use today. Add in the ability to choose a session name would seemingly solve a lot of limitations.<br><br>\-\-<br>Roebuck |
|2. | Wolfman | One other thing that gets effected is the [-]-show command.<br><br>If you want to do show on [a] different pot then the default one , you need to use the session parameter to specify the pot name. This seems inconsistent and illogical. |

**Comment by jsteube** [comment]
I think it's safe to use a fixed filename for the potfile. I don't see any good reason for a session-depending filename for the potfile. I've pushed the change to latest master.
